name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_REPO: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPO }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix={{branch}}-

    - name: Read Makefile variables
      id: makefile-vars
      run: |
        COMFYUI_VERSION=$(make -f Makefile -s -n docker-build | grep -o 'COMFYUI_VERSION=[^[:space:]]*' | cut -d'=' -f2 | head -1)
        COMFYUI_MANAGER_VERSION=$(make -f Makefile -s -n docker-build | grep -o 'COMFYUI_MANAGER_VERSION=[^[:space:]]*' | cut -d'=' -f2 | head -1)
        echo "comfyui_version=${COMFYUI_VERSION:-9da397ea2f271080406f0c14cf4f0db7221ddf70}" >> $GITHUB_OUTPUT
        echo "comfyui_manager_version=${COMFYUI_MANAGER_VERSION:-a8524508fe121cbf7d4efbfe52d203685586c685}" >> $GITHUB_OUTPUT

    - name: Build and push ComfyUI image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/comfyui.Dockerfile
        push: true
        tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPO }}:comfyui-${{ steps.makefile-vars.outputs.comfyui_version }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          COMFYUI_VERSION=${{ steps.makefile-vars.outputs.comfyui_version }}
          COMFYUI_MANAGER_VERSION=${{ steps.makefile-vars.outputs.comfyui_manager_version }}
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and push ComfyUI Jupyter image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/comfyui-jupyter.Dockerfile
        push: true
        tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPO }}:comfyui-jupyter-${{ steps.makefile-vars.outputs.comfyui_version }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          BASE_IMAGE=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPO }}:comfyui-${{ steps.makefile-vars.outputs.comfyui_version }}
        platforms: linux/amd64
        cache-from: type=gha
        cache-to: type=gha,mode=max